version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/vscode-extension"
      - "/vscode-extension-self-contained"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
