version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/vscode-extension-self-contained"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/vscode-extension"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"